name: Publish Package to npmjs
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: deploy
        env:
          NPM_TOKEN: ${{secret.NPM_TOKEN}}
        run: |
          cp ./package.json ./dist/
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > ./dist/.npmrc
          npm publish ./dist
